# Accessing and Displaying Student Data

During this tutorial we will explore a simple student dataset.  The main goal of this tutorial is to:

* Learn how to access simple comma separated text data (CSV)
* Learn how to obtain basic statistics of different types of variables
* Visualize the distribution of different types of variables
* Obtain contingency tables for categorical and ordinal variables 
* Obtain correlation graphs for numerical variables
* Obtain boxplots for relations between categorical/ordinal variables and numerical variables
* Create a Learning Analytics dashboard to explore the dataset

This dataset is available in https://archive.ics.uci.edu/ml/datasets/student+performance and correspond to students of Portuguese (in Portugal). 

## Step 0:  Initializing Notebook parameters

This step is just needed to make this notebook work.  You should not do it in R.

In [1]:
options(repr.plot.width = 6, repr.plot.height = 6)

## Step 1: Loading the Data

First, we will start with simple comma separated text data (CSV).  Please inspect <a href="https://raw.githubusercontent.com/xaoch/BLA2_2019/master/Week2/Tutorial/data/student-por.csv?token=AAGTX2BJ3A6HTQEMJ3IOHNK5N7TES">the file</a> to see the structure of the text. 

You can see that the first line usually contains the name of the variables, separated not by comma this time, but by a semicolon (";"):

<pre>
school;sex;age;address;famsize;Pstatus;Medu;Fedu;Mjob;Fjob;reason;guardian;traveltime;studytime;failures;schoolsup;famsup;paid;activities;nursery;higher;internet;romantic;famrel;freetime;goout;Dalc;Walc;health;absences;G1;G2;G3
</pre>

If you want to know the meaning of each one of this variables, you should consult the metadata of the dataset:

1. school - student's school (binary: 'GP' - Gabriel Pereira or 'MS' - Mousinho da Silveira)

2. sex - student's sex (binary: 'F' - female or 'M' - male)

3. age - student's age (numeric: from 15 to 22)

4. address - student's home address type (binary: 'U' - urban or 'R' - rural)

5. famsize - family size (binary: 'LE3' - less or equal to 3 or 'GT3' - greater than 3)

6. Pstatus - parent's cohabitation status (binary: 'T' - living together or 'A' - apart)

7. Medu - mother's education (numeric: 0 - none, 1 - primary education (4th grade), 2 â€“ 5th to 9th grade, 3 â€“ secondary education or 4 â€“ higher education)

8. Fedu - father's education (numeric: 0 - none, 1 - primary education (4th grade), 2 â€“ 5th to 9th grade, 3 â€“ secondary education or 4 â€“ higher education)

9. Mjob - mother's job (nominal: 'teacher', 'health' care related, civil 'services' (e.g. administrative or police), 'at_home' or 'other')

10. Fjob - father's job (nominal: 'teacher', 'health' care related, civil 'services' (e.g. administrative or police), 'at_home' or 'other')

11. reason - reason to choose this school (nominal: close to 'home', school 'reputation', 'course' preference or 'other')

12. guardian - student's guardian (nominal: 'mother', 'father' or 'other')

13. traveltime - home to school travel time (numeric: 1 - <15 min., 2 - 15 to 30 min., 3 - 30 min. to 1 hour, or 4 - >1 hour)

14. studytime - weekly study time (numeric: 1 - <2 hours, 2 - 2 to 5 hours, 3 - 5 to 10 hours, or 4 - >10 hours)

15. failures - number of past class failures (numeric: n if 1<=n<3, else 4)

16. schoolsup - extra educational support (binary: yes or no)

17. famsup - family educational support (binary: yes or no)

18. paid - extra paid classes within the course subject (Math or Portuguese) (binary: yes or no)

19. activities - extra-curricular activities (binary: yes or no)

20. nursery - attended nursery school (binary: yes or no) 

21. higher - wants to take higher education (binary: yes or no) 

22. internet - Internet access at home (binary: yes or no) 

23. romantic - with a romantic relationship (binary: yes or no) 

24. famrel - quality of family relationships (numeric: from 1 - very bad to 5 - excellent) 

25. freetime - free time after school (numeric: from 1 - very low to 5 - very high) 

26. goout - going out with friends (numeric: from 1 - very low to 5 - very high) 

27. Dalc - workday alcohol consumption (numeric: from 1 - very low to 5 - very high) 

28. Walc - weekend alcohol consumption (numeric: from 1 - very low to 5 - very high) 

29. health - current health status (numeric: from 1 - very bad to 5 - very good) 

30. absences - number of school absences (numeric: from 0 to 93) 

These grades are related with the course subject: 

31. G1 - first period grade (numeric: from 0 to 20) 

31. G2 - second period grade (numeric: from 0 to 20) 

32. G3 - final grade (numeric: from 0 to 20, output target)

Then the file contains several text rows.  Each row is the values corresponding to one student.

<pre>
"GP";"F";18;"U";"GT3";"A";4;4;"at_home";"teacher";"course";"mother";2;2;0;"yes";"no";"no";"no";"yes";"yes";"no";"no";4;3;4;1;1;3;4;"0";"11";11
</pre>

We will read this text file into an R dataset with the following command:

In [3]:
student_data<-read.table("student-por.csv",sep=";",header=TRUE)
head(student_data)

school sex age address famsize Pstatus Medu Fedu Mjob     Fjob     ... famrel
1 GP     F   18  U       GT3     A       4    4    at_home  teacher  ... 4     
2 GP     F   17  U       GT3     T       1    1    at_home  other    ... 5     
3 GP     F   15  U       LE3     T       1    1    at_home  other    ... 4     
4 GP     F   15  U       GT3     T       4    2    health   services ... 3     
5 GP     F   16  U       GT3     T       3    3    other    other    ... 4     
6 GP     M   16  U       LE3     T       4    3    services other    ... 5     
  freetime goout Dalc Walc health absences G1 G2 G3
1 3        4     1    1    3      4         0 11 11
2 3        3     1    1    3      2         9 11 11
3 3        2     2    3    3      6        12 13 12
4 2        2     1    1    5      0        14 14 14
5 3        2     1    2    5      0        11 13 13
6 4        2     1    2    5      6        12 12 13

<font color="darkblue">**Explanation:**

The first line is calling to the function *read.table*.  This function reads a CSV file ("student-por.csv") that is in the same directory that this tutorial.  As there are different types of CSV files, we should specify some option.  The first option is *sep*, that specify which is the character that separate different values.  In this case, the character is a ";".  The secon option is *header* that specify if the file have a first line that contains the name of the variables.  In this case, our file has such a line, so we set this option to *TRUE*. The data read from the table is assigned to the variable *student_data* using the assign symbol (*<-*). Now, we are able to access the data throgh this variable.

The second line "*head(student_data)*" just use the *head* function to present the first lines of the information stored in the *student_data* dataset.</font>

## Step 2: Variables Distributions

Once we have the data into R, we can start exploring our dataset.  The type of exploring will depend on the type of varible.  

Usually we find 3 main types of variables in our data: Nominal, Ordinal and Numerical. If you want to know more, check this <a href="https://towardsdatascience.com/data-types-in-statistics-347e152e8bee"> link </a> 

### Exploring Nominal Data

The best way to get an idea of the distribution of data of nominal variables is to count how many students have a given nominal value.  For example, it will be useful to know how many male and female students were considered into the dataset.  This information is stored in the "sex" column of the dataset.  To count the frequency of each value we will use a simple R command:

In [5]:
table(student_data$sex)


  F   M 
383 266 

<font color="darkblue">**Explanation:**

First, we need to let R know that we want to work over a single variable in the dataset.  For that, we use the "*student_data$sex*" expression.  R interprets what is after the *$* as the name of one of the data columns.  The function table create a frequency table of the different values of that variable. 

The result tell use that there are 383 female (F) students and 266 male (M) students.</font>

We can do the same for other nominal variables in the dataset:

In [6]:
table(student_data$guardian)


father mother  other 
   153    455     41 

<font color="darkblue">**Explanation:**

Now we get the distribution of values for who is the guardian of the students.  It seems that 41 of the students are represented at school by somebody else apart from their mother or father.</font>

While numbers are a good way to understand the difference between few nominal values, usually we want to have a graphical representation of the difference frequencies.  

There are several types of graphs that can be used, and which one you select will depend on the application.  For this example, we will use a Pie Chart.

In [11]:
nominal_data<-as.data.frame(table(student_data$guardian))
colnames(nominal_data)<-c("Name","Freq")
pct <- round(nominal_data$Freq/sum(nominal_data$Freq)*100)
labels<-paste(nominal_data$Name,"-",pct,"%")
pie(nominal_data$Freq,labels, main="Distribution of Guardians")

<font color="darkblue">**Explanation:**
<br/>
The first line uses the *as.data.frame* function to convert the frequency table *table(student_data\$guardian)* into a new dataset that we can use to create our chart.  This new dataset is stored in the variable *nominal_data*.

<br/>
The second line assign a name to the columns of this new dataset.  The first column, containing the name of the nominal value will be named "Name" and the second column, containing the frequency of that value will be named "Freq".  We use the *colnames* function to assign these names.

<br/>
The third line calculates the percentages of each one of the different nominal values.  It takes the frequency of the value (*nominal_data\$Freq*) and divides it by the sum of all the frequencies (*sum(nominal_dat\$Freq)*).  Then it is multiplied by 100 and rounded to the closest integer (*round* function).

<br/>
The fourth line create the labels for the graph based on the name of the nominal value (*nominal_data\$Name*), a dash, the percentage and finally a percentage sign.  The *paste* function is used to join several strings or texts.  These labels are stored in the variable labels.

<br/>
Finally, the fifth line crete the pie chart.  The first argument to the function is the frequencies (*nominal_data$Freq*), the second parameter is the label for each category (*labels*).  We add a title to the pie chart with the option *main*. 

<br/>
In this graph, it is very clear that the majority of students is represented by their mothers.
</font>

### Exploring Ordinal Data

Very similar to nominal data is ordinal data.  The main difference is that the order of the categories is important as they should be ordered.  In the same way, we can use a frequency table to explore the distribution of this variables:

In [12]:
table(student_data$health)


  1   2   3   4   5 
 90  78 124 108 249 

<font color="darkblue">**Explanation:**
<br/>
We use the *table* function to obtain the frequency for different values of the Health variable.  As we can see in the metadata, this variable has five different values with an attached meaning: 
    <pre>
    health - current health status (numeric: from 1 - very bad to 5 - very good)
    </pre>
As we can see in the data, most students have good or very good health, but a not small amount seem to have some illness.
</font>

If an ordinal variable is represented using numerical values, as in the case of health, R presupones that it is a numeric variable.  To avoid confusion, it is better to explicitly convert those numbers into factors.

In [13]:
health_factor<-factor(student_data$health, order = TRUE, levels = c(1, 2, 3,4,5))

<font color="darkblue">**Explanation:**
<br/>
The *factor* function is used to convert numerical values into factors.  The options to this function are *order* that let us know that this variable is ordinal and the *levels* that represent the different values that the factor can take.  We store this factors into a new variable *health_factor*
</font>

In the same way that we did for the nominal variables, we will visualize ordinal variables, this time using a Bar Chart.

In [17]:
plot(health_factor,col = rainbow(5),main="Distribution",xlab="Health",ylab="Students")

<font color="darkblue">**Explanation:**
<br/>
We use the *plot* function to show a Bar Chart of the health_factors.  The plot function takes as arguments the values to be represented (*health_factor*), five colors taken from the *rainbow* function "*col=rainbow(5)*", the title of the graph (*main*), the label of the x axis (*xlab*) and the label of the y axis (*ylab*). 
</font>

We can do the same for another ordinal value in the dataset:

In [18]:
mother_education<-factor(student_data$Medu, order = TRUE, levels = c(0, 1, 2,3,4))
plot(mother_education,col = rainbow(5),main="Distribution of Mother Education",xlab="Education Level",ylab="Students")

<font color="darkblue">**Explanation:**
<br/>
Notice that mother education hat 5 levels, but numbered from 0 to 4.  
</font>

### Exploring Numerical Data

The distribution of numerical data is better understood using statistics.  With numerical value, the mean and the quartiles could give you .  We can obtain that information from a numerical variable using the summary function:

In [19]:
summary(student_data$age)

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  15.00   16.00   17.00   16.74   18.00   22.00 

<font color="darkblue">**Explanation:**
<br/>
The *summary* function returns the minimum, maximum, mean, median and 1st. and 3rd. quartiles.  These values give you an idea of the distribution of numerical variables.  In this case, the age of the students fluctuates between 15 and 22 years.  The mean value for the age is 16.74.  The distribution is skewed to lower ages.
</font>

A graphical representation of this distribution is desirable.  The easiest way to do it is by an histogram.

In [47]:
hist(student_data$age,main="Age Histogram",xlab="Years",ylab="Students")

<font color="darkblue">**Explanation:**
<br/>
The *histogram* show how many values are between a given range.  In this case the range is 1 year long.  The width of the range interval (called bin) can be configured.
</font>

If the numerical variable is continuous or have a large amount of distinct values, a density plot is a better alternative. 

In [48]:
plot(density(student_data$absences),main="Density Plot of Absenses", xlab="Absences",ylab="Fraction of Students (from 0 to 1)")

<font color="darkblue">**Explanation:**
<br/>
The density plot is a representation of which fraction of the values have a given value.  The *density* function calculates the distribution of the values of the variable.  The *plot* function is used to show this distribution.
</font>

Another useful way to show the distribution of numerical variables are the Boxplots.  

In [20]:
summary(student_data$G3)
boxplot(student_data$G3,main="Distribution of Final Grades", ylab="Final Grade")

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   0.00   10.00   12.00   11.91   14.00   19.00 

<font color="darkblue">**Explanation:**
<br/>
The code first shows the summary of the Final Grade (G3) variable and then shows its boxplot.  The information shown in the boxplot is essentially the same that what is numerically presented in the summary.
</font>

## Step 3: Relations between Variables

While exploring single variables is interesting, much more information is usually extracted by the relationships that exists between different variables.  Again how to obtain and present these relationships depends in the type of variables that are being used.

### Relationships Between Nominal and Ordinal Variables

The best way to visually explore how two nominal or ordinal variables are related, is to create a cross tabulation or more commonly know as a "Contingency Table".  

In [21]:
xt<-xtabs(~ address + Medu, data = student_data)
plot(xt, col = rainbow(5), main="Relationship between Location and Mother Education",xlab="Address",ylab="Mother Education")

<font color="darkblue">**Explanation:**
<br/>
The *xtabs* function is the responbile of calculating the relationship between the two varibles (in this case Address, a nominal variable, and Mother Education, a ordinal varible).  The first parameter for the xtabs function is the relationship formula.  This formula should be in the format "~ variable1 + variable2" where variable1 and variable2 are the variables that we want to contrast.  The second option is the dataset from which these variables will be taken.
<br/>    
The result of the *xtabs* function (*xt*) is given to the *plot* function. The second option are the colors.  There should be as many colors as there is values of the second variable.
<br/>
In this case we can observe that in rural areas, mothers tend to have lower levels of education than in urban areas.  A expected, although worrisome, fact.
</font>

### Relationship between Numerical Variables

When the relationship between numerical variables is required, the usual method is to obtain the linear correlation between them.  The best way to visually establish this correlation is the Scatter Plot.

In [63]:
cor(student_data$G1,student_data$G2)
plot(student_data$G1,student_data$G2, main="Relationship between the Grades", xlab="Points First Examination",ylab="Points Second Examination")
abline(lm(student_data$G1 ~ student_data$G2), col="red")

[1] 0.8649816

<font color="darkblue">**Explanation:**
<br/>
The first line calculate the correlation coefficient between the two variables and present it.
<br/> 
The second line graphs just plot the two varibles together, one in the x-axis and the other in the y-axis.  A linear relationship is easily spoted by a linear trend in the graph.
<br/>    
The third line estimate a linear model (*lm*) between the two variables and graph a red line to better present the relationship.
<br/>
We can found an expected high level of correlation (0.87) between the first and second examination grades.
</font>

Of course, the linear relationship is not always as clear:

In [61]:
cor(student_data$G1,student_data$age)
plot(student_data$G1,student_data$age, main="Relationship between Grade and Age", xlab="Points First Examination",ylab="Age")
abline(lm(student_data$G1 ~ student_data$age), col="red")

[1] -0.1743222

<font color="darkblue">**Explanation:**
<br/>
The is no correlation between these age and grades. 
</font>

### Relationship between Numerical and Nominal/Ordinal Variables

When we want to visually explore the relationship between nominal/ordinal variables with numerical variables, the best way is to create grouped boxplots. 

In [23]:
boxplot(G3~internet,data=student_data, main="Relationship between Final Grade and Internet Access", xlab="Internet at Home", ylab="Final Grade")

<font color="darkblue">**Explanation:**
<br/>
The *boxplot* function could also receive a relationship formula "numericalVariable ~ nominalVariable˜, together with a dataset from which to take those variables, to present several boxplots, one for each value in the nominal or ordinal Variable.
<br/>
Here we can see that there is no major difference between the mean grade between students that has and do not have internet access.
</font>

## Step 4: Creating a Learning Analytics Dashboard to Explore the Student Data

Now that we know how to explore the different variables and their relationships, we will create a very simple Learning Analytics dashboard that will enable us and others to explore the dataset.

**NOTE: All of the following code should be run into R-Studio. It will not run in this notebook.**

### Substep 0

Copy the file student_por.csv to a directory in your machine.

Open R-Studio, go to the directory where you copied the data file.  Then, set it up as the working directory.

### Substep 1

Create a new FlexDashboard.

### Substep 2

Configure the Dashboard.  The header of the FlexDashboard should look like this:

<pre>
---
title: "Student Data"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---
</pre>

<font color="darkblue">**Explanation:**
<br/>
We are telling R to create a new Flex Dashboard with the name "Student Data".  This name will appear in the top of the dashboard.
<br/>
We are telling R that the layout of the dashboard will be based on columns.
<br/>
Finally we are telling R that we will use shiny as a runtime.  This will allow us to have an interactive dashboard.
</font>

### Substep 3

Import the data and setup the initial variables.  The code is here:

<pre>
```{r setup, include=FALSE}
library(flexdashboard)

# Loading student data
student_data=read.table("student-por.csv",sep=";",header=TRUE)

# Generating variables names and types dataset
variables = names(student_data)
types=c("nominal","nominal","ordinal","nominal","nominal","nominal","ordinal","ordinal","nominal","nominal","nominal","nominal","ordinal","ordinal","ordinal","nominal","nominal","nominal","nominal","nominal","nominal","nominal","nominal","ordinal","ordinal","ordinal","ordinal","ordinal","ordinal","numerical","numerical","numerical","numerical")
var_df = data.frame(variables, types) 
```
</pre>

<font color="darkblue">**Explanation:**
<br/>
First we import the flexdashboard library.  This is needed to generate the dashboard from the code.
<br/>
Second we read the data file into the student_data variable.
<br/>
Finally we generate a dataset that will contain the name and type of all the variables.  The names of the variables are stores in the "variables" variable and the types variable contains the list of "nominal", "ordinal" or "numerical" according to the type of variable.  We use the data.frame function to create a dataframe with this information and we stored it in var_df.
</font>

### Substep 4

Create a first tab named "Distributions" with a Control and a Visualization column.  This tab will be used to explore the distributions of the different variables.  The user will select a variable from the dataset and the dashboard will present the most appropiate distribution visualization for that variable type.

<pre>
Distributions
=======================================================================

Column {data-width=300}
-----------------------------------------------------------------------

### Controls


Column 
-----------------------------------------------------------------------

### Visualization


</pre>

Run the document (Play button on the top left).  You should see an empty dashboard with just one tab and no content.  If you get an error, check with the complete file at the end of this section.

### Substep 5

Add the control to select the variable inside the Control Column:

<pre>
Column {data-width=300}
-----------------------------------------------------------------------

### Controls
```{r}
selectInput("variable", label = "Variable to show:", choices = var_df$variables, selected = "school")
```
</pre>

<font color="darkblue">**Explanation:**
<br/>
You are adding a selection control that will be assigned to the variable named "variable".  It will display the text "Variable to show:" and will have the choices contained in the list of variable names stored in the var_df dataset.  At the beginning, the variable "school" will be selected.
<br/>
</font>

Now add the visualization code inside the Visualization Column:

<pre>

Column 
-----------------------------------------------------------------------

### Visualization

```{r}

renderPlot({
  variableType =var_df[var_df$variable==input$variable,]$types
  
  if (variableType=="numerical"){
   hist(student_data[[input$variable]],main=paste("Distribution of",input$variable), xlab=input$variable,ylab="Students")
  }
  if (variableType=="ordinal"){
      factors=factor(student_data[[input$variable]], order = TRUE)
      plot(factors,col = rainbow(15),main=paste("Distribution of",input$variable),xlab=input$variable,ylab="Students")
  }
  if (variableType=="nominal"){
          plot(student_data[[input$variable]],col=rainbow(15),main=paste("Distribution of",input$variable),xlab=input$variable,ylab="Students")
  }
  })

```
</pre>

<font color="darkblue">**Explanation:**
<br/>
First, we are obtaining the type of the variable that is selected in the control.  For this, we search in the var_df dataset a row in which the value of the variable name "var_df\$variable" is equal to the value selected in the control ("input\$variable").  Then we obtain the value of the column type of that row.  This is the type of the variable selected in the control.  We store this type in the "variableType" variable.
<br/>
Then we start to check the value of that type.  First we check if the type of the selected variable is numerical "if (variableType=="numerical")".  If it is numerical we should plot the histogram of that variable.  We select that variable with the "student_data[[input\$variable]]".
<br/>
Then we check fi the value of the type is ordinal.  If it is ordinal, we first convert it into factors and then we plot those factors.
<br/>
Finally, we check if the type is nominal.  If it is nominal, we just plot that variable.
</font>

Now you can run the document again.  If it correct you should see different visualizations for different types of variables.

### Substep 6

Create a new tab named "Relationships" with two columns, one named Controls and one named Visualization.  In this tab the user will user will first select one variable.  Based on this selection, a second variable should be choosen (to avoid selecting twice the same variable).  The dashboard then will present the best visualization for the relation between these two variables.

<pre>
Relationships
=======================================================================

Column {data-width=300}
-----------------------------------------------------------------------

### Controls


Column 
-----------------------------------------------------------------------

### Visualization

</pre>

Then add the following code into the "Controls" column:


<pre>

```{r}
selectInput("variable1", label = "First Variable:",
            choices = var_df$variables, selected = "school")

uiOutput("secondSelection")

output$secondSelection = renderUI({
                selectInput("variable2", label="Second Variable:", 
                choices = var_df[var_df$variable!=input$variable1,]$variables, selected=var_df[var_df$variable!=input$variable1,]$variables[0])
        })
```

</pre>

<font color="darkblue">**Explanation:**
<br/>
The first control is a selection, similar to the one in the previous tab.  It is used to select the first variable.
<br/>
The second part is a little more complicated because it will make the second selection control dependandt of the selection of the first control.  Each time that the first control is updated, we will crete a second control that will contain all the variables, except the one that was already selected in the first control, the choices are all the variables names that are not input$variable1.  The first variable of this list will be selected at the beginning. 
<br/>
</font>

Finally, add the following code inside the "Visualization" column:


<pre>

```{r}

renderPlot({
    
    type1=var_df[var_df$variable==input$variable1,]$types
    type2=var_df[var_df$variable==input$variable2,]$types
    title=paste("Relationship between",input$variable1,"and",input$variable2)
    
    if (type1=="numerical" & type2=="numerical"){
        plot(student_data[[input$variable1]],student_data[[input$variable2]],main=title,xlab=input$variable1,ylab=input$variable2)
    }
    
    if(type1=="numerical" & (type2=="ordinal" | type2=="nominal")){
       formula=as.formula(paste(input$variable1,"~",input$variable2)) 
       boxplot(formula,data=student_data,main=title,xlab=input$variable1,ylab=input$variable2)    
    }
    
    if((type1=="ordinal" | type1=="nominal") & (type2=="ordinal" | type2=="nominal")){
      formula=as.formula(paste("~",input$variable1,"+",input$variable2))  
      xt=xtabs(formula, data = student_data)
      plot(xt, col = rainbow(15), main=title,xlab=input$variable1,ylab=input$variable2)
    }
    
    if((type1=="ordinal" | type1=="nominal") & type2=="numerical"){
      formula=as.formula(paste(input$variable2,"~",input$variable1)) 
      boxplot(formula,data=student_data,main=title,xlab=input$variable1,ylab=input$variable2)
    }
  })

```
</pre>


<font color="darkblue">**Explanation:**
<br/>
This code check the type of the two variables and decide which visualization to present.  The "&" is the logic operator "AND", "|" is the logical operator "OR".  The logic is a follows:
If the type of the variable one is numerical and the type of the variable two is also numerical, plot the two variables in a scater plot.
If the type of the variable one is numerical and the type of the variable two is either ordinal or nominal, create a formula from the names of the variables and plot the boxplots.
If the type of the variable one is either ordinal or nominal and the type of the variable two is also either ordinal or nomial, create a contigency table (xtabs) and plot it.
If the type of the variable one is either ordinal or nominal and the type of the variable two is numerical, create a formula inverting the order and then plot the boxplot.
<br/>
</font>

Run the document.  If you have the correct code, you can now go to the second tab "Relationships" and compare two types of variables.

### Substep 7

Finally add this informative tab with the metadata about the dataset.

<pre>
Dataset Metadata
=======================================================================


Column 
-----------------------------------------------------------------------

### Variable Meaning and Values

1. school - student's school (binary: 'GP' - Gabriel Pereira or 'MS' - Mousinho da Silveira)

2. sex - student's sex (binary: 'F' - female or 'M' - male)

3. age - student's age (numeric: from 15 to 22)

4. address - student's home address type (binary: 'U' - urban or 'R' - rural)

5. famsize - family size (binary: 'LE3' - less or equal to 3 or 'GT3' - greater than 3)

6. Pstatus - parent's cohabitation status (binary: 'T' - living together or 'A' - apart)

7. Medu - mother's education (numeric: 0 - none, 1 - primary education (4th grade), 2 â€“ 5th to 9th grade, 3 â€“ secondary education or 4 â€“ higher education)

8. Fedu - father's education (numeric: 0 - none, 1 - primary education (4th grade), 2 â€“ 5th to 9th grade, 3 â€“ secondary education or 4 â€“ higher education)

9. Mjob - mother's job (nominal: 'teacher', 'health' care related, civil 'services' (e.g. administrative or police), 'at_home' or 'other')

10. Fjob - father's job (nominal: 'teacher', 'health' care related, civil 'services' (e.g. administrative or police), 'at_home' or 'other')

11. reason - reason to choose this school (nominal: close to 'home', school 'reputation', 'course' preference or 'other')

12. guardian - student's guardian (nominal: 'mother', 'father' or 'other')

13. traveltime - home to school travel time (numeric: 1 - < 15 min., 2 - 15 to 30 min., 3 - 30 min. to 1 hour, or 4 - >1 hour)

14. studytime - weekly study time (numeric: 1 - < 2 hours, 2 - 2 to 5 hours, 3 - 5 to 10 hours, or 4 - >10 hours)

15. failures - number of past class failures (numeric: n if 1 < = n < 3, else 4)

16. schoolsup - extra educational support (binary: yes or no)

17. famsup - family educational support (binary: yes or no)

18. paid - extra paid classes within the course subject (Math or Portuguese) (binary: yes or no)

19. activities - extra-curricular activities (binary: yes or no)

20. nursery - attended nursery school (binary: yes or no) 

21. higher - wants to take higher education (binary: yes or no) 

22. internet - Internet access at home (binary: yes or no) 

23. romantic - with a romantic relationship (binary: yes or no) 

24. famrel - quality of family relationships (numeric: from 1 - very bad to 5 - excellent) 

25. freetime - free time after school (numeric: from 1 - very low to 5 - very high) 

26. goout - going out with friends (numeric: from 1 - very low to 5 - very high) 

27. Dalc - workday alcohol consumption (numeric: from 1 - very low to 5 - very high) 

28. Walc - weekend alcohol consumption (numeric: from 1 - very low to 5 - very high) 

29. health - current health status (numeric: from 1 - very bad to 5 - very good) 

30. absences - number of school absences (numeric: from 0 to 93) 

These grades are related with the course subject: 

31. G1 - first period grade (numeric: from 0 to 20) 

31. G2 - second period grade (numeric: from 0 to 20) 

32. G3 - final grade (numeric: from 0 to 20, output target)

</pre>

### Substep 8

Run the document and check that it is working as desired.  If not, copy the code from <a href="https://github.com/xaoch/BLA2_2019/blob/master/Week2/Tutorial/sdd.Rmd">this file</a>.

### Substep 9

Plublish the dashboard in shinyapps.io (Plublish on R-Studio)

### Substep 10

Send the link of your published dashbaord as an answer in the NYU Classes site.